[package]
name = "no-std-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-list = "0.1.0"
pin-project = "1.1.3"
spin = "0.9.8"

[dev-dependencies]
pollster = "0.3.0"
